id: AB503B7CC
title: A Concise Supplication to the Most Noble Tārā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:49:20.471958
  last_modified_at: 2022-02-28 22:49:20.471965
